### ISSUE TITLE
KeyError: 'TODO_DB_1_PORT_27017_TCP_ADDR'

### ISSUE THREAD

**Issue by kaihendry** [kpurdon/docker-flask-todo#1]
http://s.natalian.org/2016-02-16/dc-flask.txt

**Comment by kpurdon** [comment]
Most likely docker has changed this env variable in the many new releases. I am not actively maintaining this example code and unfortunately do not have time to dig into this.

**Comment by krishnasathyanarayana** [comment]
Try DOCKERFLASKTODO_DB_1_PORT_27017_TCP_PORT property

**Comment by krishnasathyanarayana** [comment]
DB_PORT_27017_TCP_ADDR
